// Generated by tooling/scripts/vendor-fonts.mjs — do not edit.
// Run `bun run fonts:vendor` to regenerate.

export type BundledFontSubset = {
    subset: string;
    /** Served path, also fetched by the canvas renderer for inlining. */
    url: string;
    weight: number | null;
    unicodeRange: string;
};

export type BundledFont = {
    family: string;
    /** Ready to assign to a CSS font-family declaration. */
    css: string;
    variable: boolean;
    subsets: BundledFontSubset[];
};

export const BUNDLED_FONTS: BundledFont[] = [
    {
        family: 'Inter',
        css: "'Inter', sans-serif",
        variable: true,
        subsets: [
            {
                subset: 'latin',
                url: '/fonts/inter-latin-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/inter-latin-ext-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/inter-vietnamese-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'greek',
                url: '/fonts/inter-greek-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/inter-cyrillic-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/inter-cyrillic-ext-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            }
        ]
    },
    {
        family: 'Source Serif 4',
        css: "'Source Serif 4', serif",
        variable: true,
        subsets: [
            {
                subset: 'latin',
                url: '/fonts/source-serif-4-latin-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/source-serif-4-latin-ext-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/source-serif-4-vietnamese-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'greek',
                url: '/fonts/source-serif-4-greek-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/source-serif-4-cyrillic-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/source-serif-4-cyrillic-ext-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            }
        ]
    },
    {
        family: 'JetBrains Mono',
        css: "'JetBrains Mono', monospace",
        variable: true,
        subsets: [
            {
                subset: 'latin',
                url: '/fonts/jetbrains-mono-latin-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/jetbrains-mono-latin-ext-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/jetbrains-mono-vietnamese-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'greek',
                url: '/fonts/jetbrains-mono-greek-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/jetbrains-mono-cyrillic-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/jetbrains-mono-cyrillic-ext-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            }
        ]
    },
    {
        family: 'IBM Plex Sans',
        css: "'IBM Plex Sans', sans-serif",
        variable: true,
        subsets: [
            {
                subset: 'latin',
                url: '/fonts/ibm-plex-sans-latin-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/ibm-plex-sans-latin-ext-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/ibm-plex-sans-vietnamese-wght-normal.woff2',
                weight: null,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'greek',
                url: '/fonts/ibm-plex-sans-greek-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0370-0377,U+037A-037F,U+0384-038A,U+038C,U+038E-03A1,U+03A3-03FF'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/ibm-plex-sans-cyrillic-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/ibm-plex-sans-cyrillic-ext-wght-normal.woff2',
                weight: null,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            }
        ]
    },
    {
        family: 'IBM Plex Serif',
        css: "'IBM Plex Serif', serif",
        variable: false,
        subsets: [
            {
                subset: 'latin',
                url: '/fonts/ibm-plex-serif-latin-400-normal.woff2',
                weight: 400,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin',
                url: '/fonts/ibm-plex-serif-latin-700-normal.woff2',
                weight: 700,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/ibm-plex-serif-latin-ext-400-normal.woff2',
                weight: 400,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/ibm-plex-serif-latin-ext-700-normal.woff2',
                weight: 700,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/ibm-plex-serif-vietnamese-400-normal.woff2',
                weight: 400,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/ibm-plex-serif-vietnamese-700-normal.woff2',
                weight: 700,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/ibm-plex-serif-cyrillic-400-normal.woff2',
                weight: 400,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/ibm-plex-serif-cyrillic-700-normal.woff2',
                weight: 700,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/ibm-plex-serif-cyrillic-ext-400-normal.woff2',
                weight: 400,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/ibm-plex-serif-cyrillic-ext-700-normal.woff2',
                weight: 700,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            }
        ]
    },
    {
        family: 'IBM Plex Mono',
        css: "'IBM Plex Mono', monospace",
        variable: false,
        subsets: [
            {
                subset: 'latin',
                url: '/fonts/ibm-plex-mono-latin-400-normal.woff2',
                weight: 400,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin',
                url: '/fonts/ibm-plex-mono-latin-700-normal.woff2',
                weight: 700,
                unicodeRange:
                    'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/ibm-plex-mono-latin-ext-400-normal.woff2',
                weight: 400,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'latin-ext',
                url: '/fonts/ibm-plex-mono-latin-ext-700-normal.woff2',
                weight: 700,
                unicodeRange:
                    'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/ibm-plex-mono-vietnamese-400-normal.woff2',
                weight: 400,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'vietnamese',
                url: '/fonts/ibm-plex-mono-vietnamese-700-normal.woff2',
                weight: 700,
                unicodeRange:
                    'U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20AB'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/ibm-plex-mono-cyrillic-400-normal.woff2',
                weight: 400,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic',
                url: '/fonts/ibm-plex-mono-cyrillic-700-normal.woff2',
                weight: 700,
                unicodeRange: 'U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/ibm-plex-mono-cyrillic-ext-400-normal.woff2',
                weight: 400,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            },
            {
                subset: 'cyrillic-ext',
                url: '/fonts/ibm-plex-mono-cyrillic-ext-700-normal.woff2',
                weight: 700,
                unicodeRange: 'U+0460-052F,U+1C80-1C88,U+20B4,U+2DE0-2DFF,U+A640-A69F,U+FE2E-FE2F'
            }
        ]
    }
];
